### PR TITLE
Fix edge export feature + translations

### LINKED ISSUE #193: Wrong host in download URL in Microsoft Edge
Screenshot_2019-05-27 Dashboard(1)

*Screenshot [https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Edge&browser_version=17.0 ...](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Edge&browser_version=17.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=http%3A%2F%2Fbrouter.de%2Fbrouter-web%2F%23map%3D13%2F47.7038%2F9.3653%2Fstandard%26lonlats%3D9.391594%2C47.721193%3B9.284649%2C47.694734&speed=1)*

Seems like the server request URL generated by Export is using `http://brouter.de` instead of  `http://h2096617.stratoserver.net:443`.

### LINKED ISSUE #195: Export: buttons not translated
The buttons "Close" and "Export route" in the Export dialog are not translated, although there is a key and translations, e.g. for the close button:

https://github.com/nrenner/brouter-web/blob/481b28759c9bf9952307190e5fd19d81a793eab7/locales/en.json#L114-L116

https://github.com/nrenner/brouter-web/blob/481b28759c9bf9952307190e5fd19d81a793eab7/locales/fr.json#L114-L116

https://github.com/nrenner/brouter-web/blob/481b28759c9bf9952307190e5fd19d81a793eab7/index.html#L658

### PR DESCRIPTION
**Pull request by bagage**
Fixes #193 
Fixes #195

### CODE REVIEW

File: js/control/Export.js [hunk 1]
```diff
@@ -23,7 +23,9 @@ BR.Export = L.Class.extend({
 
     _export: function() {
         var exportForm = document.forms['export'];
-        var format = exportForm['format'].value;
+        var format =
+            exportForm['format'].value ||
+            $('#export-format input:radio:checked');
```
Comment (nrenner) [inline js/control/Export.js]: This is only returning the jQuery object, not the value - I think `.val()` needs to be added:

```
> $('#export-format input:radio:checked')
jQuery.fn.init [input#format-gpx.form-check-input, prevObject: jQuery.fn.init(1)]
> $('#export-format input:radio:checked').val()
"gpx"
```

When commenting out line 27 (testing with Chrome), the download URL is fixed because `format != null`, but the file extension is: `[object Object]`.

Comment (bagage) [reply js/control/Export.js]: Damn, you're right I forgot to add it. I tested it via the dev console and then did some refactoring but then forgot it... *sight*. Thanks, as always.
